version: "2.24"

name: weather-app-shuvro

services:
    redis:
        image: redis/redis-stack-server:latest
        ports:
            - "6379:6379"

    express-api:
        # container_name: backend
        image: shuvro/wa-backend
        build: ./server
        ports:
            - "4000:4000"
        command: ["pnpm", "run", "start"]
        environment:
            - REDIS_HOST=redis

    nextjs-app:
        # container_name: frontend
        image: shuvro/wa-frontend
        build: ./client
        ports:
            - "3000:3000"
        command: ["pnpm", "run", "start"]
